export const COUNTRIES: string[] = [
    'India',
    'Afghanistan',
    'Algeria',
    'Andorra',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Belgium',
    'Bolivia',
    'Bosnia Herzegovina',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Canada',
    'Chile',
    'China',
    'Colombia',
    'Croatia',
    'Cyprus',
    'Czech Republic',
    'Democratic Republic of the Congo',
    'Denmark',
    'Ecuador',
    'Ethiopia',
    'Finland',
    'France',
    'Germany',
    'Ghana',
    'Guatemala',
    'Hong Kong SAR',
    'Hungary',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Latvia',
    'Lithuania',
    'Luxembourg',
    'Macao SAR',
    'Malaysia',
    'Malta',
    'Mexico',
    'Mongolia',
    'Myanmar',
    'Nepal',
    'Netherlands',
    'New Caledonia',
    'New Zealand',
    'Nigeria',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palestinian Territory',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Romania',
    'Russia',
    'San Marino',
    'Serbia',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'South Africa',
    'South Korea',
    'Spain',
    'Sri Lanka',
    'Svalbard and Jan Mayen',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Thailand',
    'Turkey',
    'U.S. Virgin Islands',
    'USA',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'Uzbekistan',
    'Vietnam',
    'Yemen'
]